### ISSUE TITLE
Error running simulated_data.py

### ISSUE THREAD

**Issue by parthe** [JeanKossaifi/FISTA#3]
>>python3 simulated_data.py
Traceback (most recent call last):
  File "simulated_data.py", line 1, in <module>
    from fista import Fista
  File "/mnt/d/Git local repos/FISTA/fista.py", line 535
    prox = lambda(u):prox_l11(u, self.lambda_*Lipschitz_constant)
                 ^
SyntaxError: invalid syntax

**Comment by JeanKossaifi** [comment]
I had written this for python2. It should be fine now.
